### ISSUE TITLE
Cast exception on removeSharedObject

### ISSUE THREAD

**Issue by Alfiva** [universAAL/remote#339]
_Originally Opened: @Alfiva (2013-07-09 10:56:52_)
_Originally Closed: 2013-07-15 09:35:30_

This happens when HwO Servlet bundle is started but its configuration properties is not present (I guess it´s triggered because this HwO shared object is removed, or something...)

ERROR: Bundle mw.bus.tracker.osgi [120] EventDispatcher: Error during dispatch. (java.lang.ClassCastException: org.universAAL.ri.gateway.eimanager.imp
l.security.ExportSecurityOperationInterceptor cannot be cast to org.osgi.framework.ServiceReference)
java.lang.ClassCastException: org.universAAL.ri.gateway.eimanager.impl.security.ExportSecurityOperationInterceptor cannot be cast to org.osgi.framewor
k.ServiceReference
        at org.universAAL.ri.gateway.eimanager.impl.EIOperationManager.sharedObjectRemoved(EIOperationManager.java:90)
        at org.universAAL.middleware.container.osgi.uAALBundleContainer.serviceChanged(uAALBundleContainer.java:230)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:871)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:733)
...........
And right after that it also happens with:
ERROR: Bundle mw.connectors.communication.jgroups.osgi [66] EventDispatcher: Error during dispatch. (java.lang.ClassCastException: org.universAAL.midd
leware.tracker.impl.BusMemberRegistryImpl cannot be cast to org.osgi.framework.ServiceReference)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by Alfiva** [comment]
_Original author: @d4nielek (2013-07-15 09:35:30)_

Fixed in revision 273.

**Comment by Alfiva** [comment]
issue cloed on 2013-07-15 09:35:30
