### ISSUE TITLE
NPE Starting multitenant GW due to null value in hashmap

### ISSUE THREAD

**Issue by Alfiva** [universAAL/remote#483]
I tried installing the MT GW in the legacy 3.4.1-S environment but got the following Activator start error:

Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)[:1.8.0_92]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)[:1.8.0_92]
	at org.universAAL.ri.gateway.Exporter.busMemberAdded(Exporter.java:433)
	at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl.notifyAboutPreviouslyRegisteredMembers(BusMemberRegistryImpl.java:271)
	at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl.addListener(BusMemberRegistryImpl.java:283)
	at org.universAAL.ri.gateway.Gateway.actualStart(Gateway.java:131)
	at org.universAAL.ri.gateway.Gateway.start(Gateway.java:102)

It is not important how I got there (probably because of using default security filter in configuration) but that the following code is executed. At Exporter.java line 433:

`tracked.put(member.getURI(), null);`

"tracked" is a ConcurrentHashMap, which does not allow null values.
I assume this happens as well in 3.4.2-S master branch since the code is the same at this point.

**Comment by Alfiva** [comment]
Unfortunately Exporter relies on the possibility of tracking keys whether their value is null, so simply replacing that line for tracked.remove() wouldn't work. What about having a constant value to identify as null?

P.S. Javadoc says "Like Hashtable but unlike HashMap, this class does not allow null to be used as a key or value.". I guess they really should have called it ConcurrentHashTable ;)

**Comment by Alfiva** [comment]
I have tested with a custom extension of ConcurrentHashMap that accepts null (as a token object) and, at least the NPE has disappeared. However, I have not managed to make the GW wrok properly, because members are never exported.
I always get "could not find nor create a export proxy with the given parameters for {bus member}". This happens because after `tracked.put(member.getURI(), null);`, put is never called again with good parameters instead of null. I was assuming that the Bus Tracker would call regParamsAdded after busMemberAdded but it does not.
Since I did not make this class I didn't want to start tweaking things. Let me know if you can work on this or if I am doing somethign wrong soon because I need the MT GW ASAP.

**Comment by Alfiva** [comment]
OK my bad. The Tracker does call regParamsAdded. It was just being overlooked by the Gateway because of an obscure mistake I did in my custom ConcurrentHashMap. The GW does work now as intended with my fix, sorry for the alert. Let me know if you want me to commit the fix, or if you want to test it on your end first.

**Comment by Alfiva** [comment]
I found an issue while testing this solution that may be of interest here. When including the gateway in Native Android MW, I got an exception because of missing keySet() method in ConcurrentHashMap. This method varies signature between Java 1.7 and 1.8, so be aware of that, and make sure you are compiling everything with the same version.

**Comment by Alfiva** [comment]
In line with the previous comment: Because Android uses a "custom" version of Java, its latest SDK still uses the 1.7 version of ConcurrentHashMap (or maybe just of `keyset()` ).
In order to have the Gateway working in Android, I had to make some tweaks: By declaring `tracked `as the super interface Map instead of NullConcurrentHashMap, the signature conflict of `keyset()` disappears and all works well. I am confident enough now that this fix can be pushed.

**Comment by Alfiva** [comment]
Fixed in branch b7abe03 (3.4.1-S). Merge into master if it's good enough.
