### ISSUE TITLE
MTG bundle prevents other bundles to register to any bus

### ISSUE THREAD

**Issue by uzi0espil** [universAAL/remote#493]
I have encountered a weird behaviour in universAAL whenever I add the package uAAL-RI.Gateway.Multitenant that no subscriber or service Callee can register to their respective buses . On the other hand, if you installed any bundle that register to any bus before installing MTG then MTG will fail to install.

The error generated for first case. More specifically, when a subscriber subscribes to the Context bus:
```
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1124)
        at org.universAAL.ri.gateway.Exporter.busMemberAdded(Exporter.java:433)
        at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl$TypedRegistryListener.busMemberAdded(BusMemberRegistryImpl.java:98)
        at org.universAAL.middleware.bus.model.util.RegistryMap.addBusMember(RegistryMap.java:48)
        at org.universAAL.middleware.bus.model.AbstractBus.register(AbstractBus.java:311)
        at org.universAAL.middleware.bus.member.BusMember.<init>(BusMember.java:59)
        at org.universAAL.middleware.bus.member.Subscriber.<init>(Subscriber.java:35)
        at org.universAAL.middleware.context.ContextSubscriber.<init>(ContextSubscriber.java:65)
        at org.universAAL.samples.main.CSubscriber.<init>(CSubscriber.java:25)
        at org.universAAL.samples.main.Activator.start(Activator.java:19)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2064)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-111" java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1124)
        at org.universAAL.ri.gateway.Exporter.busMemberAdded(Exporter.java:433)
        at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl$TypedRegistryListener.busMemberAdded(BusMemberRegistryImpl.java:98)
        at org.universAAL.middleware.bus.model.util.RegistryMap.addBusMember(RegistryMap.java:48)
        at org.universAAL.middleware.bus.model.AbstractBus.register(AbstractBus.java:311)
        at org.universAAL.middleware.bus.member.BusMember.<init>(BusMember.java:59)
        at org.universAAL.middleware.bus.member.Subscriber.<init>(Subscriber.java:35)
        at org.universAAL.middleware.context.ContextSubscriber.<init>(ContextSubscriber.java:65)
        at org.universAAL.context.che.ContextHistorySubscriber.<init>(ContextHistorySubscriber.java:66)
        at org.universAAL.context.che.Hub.start(Hub.java:151)
        at org.universAAL.context.che.osgi.Activator$1.run(Activator.java:87)
```

You can fast verify this issue by installing the multi-tenant gateway and then install the uAAL-Tool.log (Since it subscribes for all events, the installation of this bundle will crash with similar issue).

More information, here is the server.properties I use for MTG:
```
remote-gateway-host=localhost
socket-port=8888
security-definition-file=none
hash-key=ab55a60854e1b699c68a692f0a4980dbc5771ac32e641c89b636c00bb05c7cf5
connection-mode=server
```

**Comment by Alfiva** [comment]
This seems to be the same as #483 so perhaps we can redirect there. Anyway, that problem was solved already. Which version are you using? 3.4.2-SNAPSHOT should not have this bug, and neither 3.4.1-SNAPSHOT. However, perhaps 3.4.1-SNAPSHOT has not been re-deployed to nexus since the fix (it is a discontinued branch after all). You can either build it yourself, or wait until we deploy it again.

**Comment by amedranogil** [comment]
Please state the version of karaf, middleware and MTGW you are using.
On the other hand, if you connect to localhost, without the proper precautions, you may incur in a loop: the MTGW will connect two remote uSpaces, if those are already conected (through the discovering and peering layer of the middleware), or even the same, you can expect mayhem. But this might not be the case since you are not setting up an MTGW yet?

**Comment by amedranogil** [comment]
I agree with @Alfiva , it seems this is the same as #483 . But there might be another know issue here too.

**Comment by uzi0espil** [comment]
Ya it seems to be the same issue. However, I am using 3.4.1-SNAPSHOT. I will try to build it and see if the issue persist. Thanks

**Comment by Alfiva** [comment]
If you manage to get it working with that, let us know, because then the reason is that the last 3.4.1-S deployed in nexus does not have the fix - we would then try to re-deploy

**Comment by uzi0espil** [comment]
I have re-build and deployed 3.4.1-SNAPSHOT and the error is gone.. it seems to work fine now.

Cheers.
